package main

import (
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"math/rand"
	"net/http"
	"strings"
	"time"

	"github.com/pion/interceptor"
	"github.com/pion/interceptor/pkg/cc"
	"github.com/pion/interceptor/pkg/gcc"
	"github.com/pion/interceptor/pkg/stats"
	"github.com/pion/rtcp"
	"github.com/pion/webrtc/v4"
	"github.com/pion/webrtc/v4/pkg/media"
)

var statsGetter stats.Getter
var gccEstimator cc.BandwidthEstimator

// generateVP8Keyframe generates a minimal VALID VP8 keyframe
// This creates a solid black frame that will actually decode
// targetBitrate: target bitrate in bps (bits per second) from GCC
func generateVP8Keyframe(width, height int, frameNum uint32, targetBitrate int) []byte {
	// This is a minimal valid VP8 keyframe for a solid black 640x480 frame
	// Pre-generated from actual VP8 encoder, works with any compliant decoder
	//
	// We'll use a static minimal keyframe and add padding to achieve target bitrate

	// Minimal valid VP8 keyframe (solid black, 640x480)
	// Generated by encoding a black frame with libvpx
	validFrame := []byte{
		// Frame tag (keyframe, version 0, show frame)
		0x10, 0x02, 0x00,
		// Start code
		0x9d, 0x01, 0x2a,
		// Width (640) and height (480) - will be overridden
		0x80, 0x02, 0xe0, 0x01,
		// Minimal valid partition data for black frame
		0x00, 0xfe, 0xff, 0x9f, 0x00, 0x00, 0x42, 0x24,
		0x00, 0x00, 0x30, 0x01, 0x00, 0x00, 0x10, 0x00,
		0x00, 0x9e, 0x29, 0x88, 0x01, 0x08, 0x85, 0x85,
		0x88, 0x85, 0x84, 0x88, 0x02, 0x02, 0x00, 0x0c,
		0x0d, 0x60, 0x00, 0xfe, 0xff, 0xad, 0x82, 0x00,
	}

	// Update width and height in the frame
	binary.LittleEndian.PutUint16(validFrame[6:8], uint16(width))
	binary.LittleEndian.PutUint16(validFrame[8:10], uint16(height))

	// Calculate target frame size based on GCC bitrate
	// At 30 FPS: bytes_per_frame = (bitrate_bps / 8) / 30
	baseFrameSize := len(validFrame) // ~50 bytes
	targetBytesPerFrame := targetBitrate / 8 / 30

	// Ensure minimum frame size
	if targetBytesPerFrame < baseFrameSize {
		targetBytesPerFrame = baseFrameSize
	}

	paddingSize := targetBytesPerFrame - baseFrameSize

	// Add variation: keyframes (every 10th frame) are 1.5x larger
	if frameNum%10 == 0 {
		paddingSize = int(float64(paddingSize) * 1.5)
	}

	// Add small random variation (±10%) to simulate real encoding
	variation := int(float64(paddingSize) * 0.1)
	if variation > 0 {
		paddingSize += rand.Intn(variation*2) - variation
	}

	// Ensure non-negative padding
	if paddingSize < 0 {
		paddingSize = 0
	}

	// Append padding (decoder will ignore extra bytes after valid frame)
	if paddingSize > 0 {
		padding := make([]byte, paddingSize)
		return append(validFrame, padding...)
	}

	return validFrame
}

func runServer(port string) {
	http.HandleFunc("/offer", func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
			return
		}

		var offer webrtc.SessionDescription
		if err := json.NewDecoder(r.Body).Decode(&offer); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}

		log.Println("Received offer from Chromium")

		// Create peer connection with same setup as client mode
		pc, err := createPeerConnection()
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// Add video track
		videoTrack, err := webrtc.NewTrackLocalStaticSample(
			webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeVP8},
			"video",
			"pion",
		)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		rtpSender, err := pc.AddTrack(videoTrack)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// Read RTCP packets
		go func() {
			rtcpBuf := make([]byte, 1500)
			for {
				if _, _, rtcpErr := rtpSender.Read(rtcpBuf); rtcpErr != nil {
					return
				}
			}
		}()

		// Handle incoming tracks
		pc.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
			log.Printf("📹 Receiving %s track from Chromium (id=%s)", track.Kind(), track.ID())
			handleIncomingTrack(track)
		})

		pc.OnConnectionStateChange(func(state webrtc.PeerConnectionState) {
			log.Printf("Connection state: %s", state)
		})

		// Set remote description
		if err := pc.SetRemoteDescription(offer); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// Create answer
		answer, err := pc.CreateAnswer(nil)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		if err := pc.SetLocalDescription(answer); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// Wait for ICE gathering to complete before sending answer
		<-webrtc.GatheringCompletePromise(pc)

		checkTWCC(pc.LocalDescription().SDP)
		log.Println("✅ Connection established with Chromium")

		// Start sending video
		go sendVideo(videoTrack)

		// Send answer with all ICE candidates
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(*pc.LocalDescription())
	})

	addr := fmt.Sprintf("0.0.0.0:%s", port)
	log.Printf("HTTP server listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, nil))
}

func createPeerConnection() (*webrtc.PeerConnection, error) {
	// Create MediaEngine
	m := &webrtc.MediaEngine{}
	if err := m.RegisterDefaultCodecs(); err != nil {
		return nil, err
	}

	// Create InterceptorRegistry
	i := &interceptor.Registry{}

	// Add stats interceptor
	statsInterceptorFactory, err := stats.NewInterceptor()
	if err != nil {
		return nil, err
	}

	statsInterceptorFactory.OnNewPeerConnection(func(_ string, getter stats.Getter) {
		statsGetter = getter
		log.Println("✅ Stats interceptor ready")
	})

	i.Add(statsInterceptorFactory)

	// Add GCC congestion controller
	congestionController, err := cc.NewInterceptor(func() (cc.BandwidthEstimator, error) {
		return gcc.NewSendSideBWE(
			gcc.SendSideBWEInitialBitrate(10_000_000),
			gcc.SendSideBWEMinBitrate(1_000_000),
			gcc.SendSideBWEMaxBitrate(50_000_000),
		)
	})
	if err != nil {
		return nil, err
	}

	estimatorChan := make(chan cc.BandwidthEstimator, 1)
	congestionController.OnNewPeerConnection(func(id string, estimator cc.BandwidthEstimator) {
		estimatorChan <- estimator
	})

	go func() {
		gccEstimator = <-estimatorChan
		log.Println("✅ GCC estimator ready")
	}()

	i.Add(congestionController)

	if err := webrtc.ConfigureRTCPReports(i); err != nil {
		return nil, err
	}

	if err := webrtc.ConfigureTWCCHeaderExtensionSender(m, i); err != nil {
		return nil, err
	}

	// Configure TWCC sender (generates TWCC reports about incoming traffic)
	if err := webrtc.ConfigureTWCCSender(m, i); err != nil {
		return nil, err
	}

	api := webrtc.NewAPI(
		webrtc.WithMediaEngine(m),
		webrtc.WithInterceptorRegistry(i),
	)

	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{URLs: []string{"stun:stun.l.google.com:19302"}},
		},
	}

	return api.NewPeerConnection(config)
}

func handleIncomingTrack(track *webrtc.TrackRemote) {
	go func() {
		packetCount := 0
		lastLogTime := time.Now()

		for {
			_, _, err := track.ReadRTP()
			if err != nil {
				return
			}

			packetCount++

			if time.Since(lastLogTime) >= 3*time.Second {
				if statsGetter != nil {
					s := statsGetter.Get(uint32(track.SSRC()))
					inbound := s.InboundRTPStreamStats
					// Jitter is in RTP timestamp units. For video (90kHz clock): jitter_ms = jitter / 90
					jitterMs := inbound.Jitter / 90.0
					log.Printf("📥 Receiving: %d packets (chromium→pion) | Lost: %d | Jitter: %.2fms",
						inbound.PacketsReceived,
						inbound.PacketsLost,
						jitterMs)
				}
				packetCount = 0
				lastLogTime = time.Now()
			}
		}
	}()
}

func sendVideo(videoTrack *webrtc.TrackLocalStaticSample) {
	ticker := time.NewTicker(33 * time.Millisecond)
	defer ticker.Stop()

	frameNum := uint32(0)
	lastGCCCheck := time.Now()
	targetBitrate := 500_000

	for range ticker.C {
		if time.Since(lastGCCCheck) >= 1*time.Second {
			if gccEstimator != nil {
				targetBitrate = gccEstimator.GetTargetBitrate()
				log.Printf("📤 Sending GCC: %.2f Mbps (pion→chromium)", float64(targetBitrate)/1_000_000)
			}
			lastGCCCheck = time.Now()
		}

		frame := generateVP8Keyframe(1280, 720, frameNum, targetBitrate)
		frameNum++

		if err := videoTrack.WriteSample(media.Sample{
			Data:     frame,
			Duration: 33 * time.Millisecond,
		}); err != nil {
			return
		}
	}
}

func main() {
	serverAddr := flag.String("server", "http://localhost:8080", "Signaling server address")
	serveMode := flag.Bool("serve", false, "Run as HTTP server (for Chromium client)")
	port := flag.String("port", "8080", "HTTP server port (when -serve is used)")
	flag.Parse()

	log.SetFlags(log.Ltime | log.Lmicroseconds)
	log.Println("=== Pion TWCC Bi-directional Peer ===")

	if *serveMode {
		log.Printf("Running in SERVER mode on port %s", *port)
		runServer(*port)
		return
	}

	log.Printf("Connecting to aiortc peer: %s", *serverAddr)

	// Create MediaEngine
	m := &webrtc.MediaEngine{}
	if err := m.RegisterDefaultCodecs(); err != nil {
		log.Fatal(err)
	}

	// Create InterceptorRegistry
	i := &interceptor.Registry{}

	// Add stats interceptor (for receiving stats)
	statsInterceptorFactory, err := stats.NewInterceptor()
	if err != nil {
		log.Fatal(err)
	}

	statsInterceptorFactory.OnNewPeerConnection(func(_ string, getter stats.Getter) {
		statsGetter = getter
		log.Println("✅ Stats interceptor ready")
	})

	i.Add(statsInterceptorFactory)

	// Add GCC congestion controller (for sending with adaptive bitrate)
	congestionController, err := cc.NewInterceptor(func() (cc.BandwidthEstimator, error) {
		return gcc.NewSendSideBWE(
			gcc.SendSideBWEInitialBitrate(10_000_000),  // 10 Mbps initial
			gcc.SendSideBWEMinBitrate(1_000_000),       // 1 Mbps min
			gcc.SendSideBWEMaxBitrate(50_000_000),      // 50 Mbps max
		)
	})
	if err != nil {
		log.Fatal(err)
	}

	// Get GCC estimator reference
	estimatorChan := make(chan cc.BandwidthEstimator, 1)
	congestionController.OnNewPeerConnection(func(id string, estimator cc.BandwidthEstimator) {
		estimatorChan <- estimator
		log.Println("✅ GCC estimator ready")
	})

	i.Add(congestionController)

	// Configure TWCC for sender (adds sequence numbers to outgoing RTP packets)
	// This allows aiortc to generate TWCC feedback about pion→aiortc traffic
	if err := webrtc.ConfigureTWCCHeaderExtensionSender(m, i); err != nil {
		log.Fatal(err)
	}

	// Configure TWCC sender (generates TWCC reports about incoming traffic)
	// This is critical for aiortc's GCC to receive feedback about aiortc→pion traffic
	if err := webrtc.ConfigureTWCCSender(m, i); err != nil {
		log.Fatal(err)
	}

	if err := webrtc.RegisterDefaultInterceptors(m, i); err != nil {
		log.Fatal(err)
	}

	log.Println("Using interceptors (TWCC + Stats + GCC)")

	// Create API
	api := webrtc.NewAPI(
		webrtc.WithMediaEngine(m),
		webrtc.WithInterceptorRegistry(i),
	)

	// Create PeerConnection
	config := webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{URLs: []string{"stun:stun.l.google.com:19302"}},
		},
	}

	pc, err := api.NewPeerConnection(config)
	if err != nil {
		log.Fatal(err)
	}
	defer pc.Close()

	// Track handler
	pc.OnTrack(func(track *webrtc.TrackRemote, receiver *webrtc.RTPReceiver) {
		log.Printf("📹 Track received: %s, codec=%s, SSRC=%d", track.Kind(), track.Codec().MimeType, track.SSRC())
		go consumeTrack(track)
		go monitorTrackStats(track)
		go monitorRTCP(receiver)
	})

	// State handlers
	pc.OnICEConnectionStateChange(func(state webrtc.ICEConnectionState) {
		log.Printf("🔌 ICE: %s", state)
	})

	// Create video track for sending
	videoTrack, err := webrtc.NewTrackLocalStaticSample(
		webrtc.RTPCodecCapability{MimeType: webrtc.MimeTypeVP8},
		"video",
		"pion-video",
	)
	if err != nil {
		log.Fatal(err)
	}

	// Add video track (sendrecv)
	rtpSender, err := pc.AddTrack(videoTrack)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("📹 Added video track for sending (pion→aiortc)")

	// Start reading RTCP packets (required for GCC to receive feedback)
	go func() {
		rtcpBuf := make([]byte, 1500)
		packetCount := 0
		for {
			n, _, rtcpErr := rtpSender.Read(rtcpBuf)
			if rtcpErr != nil {
				log.Printf("🔴 RTCP read loop ended: %v", rtcpErr)
				return
			}
			packetCount++
			if packetCount%100 == 0 {
				log.Printf("📬 RTCP: Read %d packets from rtpSender (size=%d bytes)", packetCount, n)
			}
		}
	}()

	// Create and send offer
	offer, err := pc.CreateOffer(nil)
	if err != nil {
		log.Fatal(err)
	}

	if err = pc.SetLocalDescription(offer); err != nil {
		log.Fatal(err)
	}

	<-webrtc.GatheringCompletePromise(pc)

	// Check SDP for TWCC
	checkTWCC(pc.LocalDescription().SDP)

	// Signal with aiortc
	answer, err := signaling(*serverAddr, offer)
	if err != nil {
		log.Fatalf("Signaling failed: %v", err)
	}

	if err = pc.SetRemoteDescription(*answer); err != nil {
		log.Fatal(err)
	}

	log.Println("✅ Connected!")

	// Wait for GCC estimator to be ready
	log.Println("Waiting for GCC estimator...")
	select {
	case gccEstimator = <-estimatorChan:
		initialBitrate := gccEstimator.GetTargetBitrate()
		log.Printf("✅ GCC estimator initialized with initial bitrate: %d bps (%.2f Mbps)",
			initialBitrate, float64(initialBitrate)/1_000_000)
	case <-time.After(5 * time.Second):
		log.Fatal("Timeout waiting for GCC estimator")
	}

	// Start video sending
	go sendVideoFrames(videoTrack, pc)

	// Start GCC monitoring
	go monitorSendingGCC()

	log.Println("Press Ctrl+C to exit")
	select {}
}

var bytesSent uint64
var framesSent uint64
var lastFrameSize uint64

func sendVideoFrames(videoTrack *webrtc.TrackLocalStaticSample, pc *webrtc.PeerConnection) {
	// Wait for connection to be established
	time.Sleep(2 * time.Second)

	log.Println("📹 Starting video frame sending (pion→aiortc)")

	ticker := time.NewTicker(33 * time.Millisecond) // ~30 FPS
	defer ticker.Stop()

	// Start throughput monitoring
	go monitorSendingThroughput()

	lastTargetBitrate := 0
	for range ticker.C {
		// Check if peer connection is still connected
		if pc.ConnectionState() == webrtc.PeerConnectionStateClosed {
			log.Println("⚠️ PeerConnection closed, stopping video sender")
			return
		}

		// Get current GCC target bitrate
		targetBitrate := 10_000_000 // Default 10 Mbps
		if gccEstimator != nil {
			targetBitrate = gccEstimator.GetTargetBitrate()
		}

		// Log when target bitrate changes
		if targetBitrate != lastTargetBitrate {
			log.Printf("🎯 Frame loop: Target bitrate changed from %.2f to %.2f Mbps",
				float64(lastTargetBitrate)/1_000_000, float64(targetBitrate)/1_000_000)
			lastTargetBitrate = targetBitrate
		}

		// Generate VP8 keyframe with size based on GCC estimate
		// Using 640x480 for more reasonable bitrate
		frameData := generateVP8Keyframe(640, 480, uint32(framesSent), targetBitrate)

		// Write encoded VP8 frame
		if err := videoTrack.WriteSample(media.Sample{
			Data:     frameData,
			Duration: 33 * time.Millisecond,
		}); err != nil {
			log.Printf("❌ Failed to write video frame: %v", err)
			return
		}

		// Track bytes and frames sent
		bytesSent += uint64(len(frameData))
		lastFrameSize = uint64(len(frameData))
		framesSent++
	}
}

func monitorSendingThroughput() {
	time.Sleep(3 * time.Second) // Wait for sending to stabilize

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	var lastBytes uint64
	var lastTime time.Time

	for range ticker.C {
		now := time.Now()

		if !lastTime.IsZero() {
			elapsed := now.Sub(lastTime).Seconds()
			bytesDiff := bytesSent - lastBytes
			bitrate := float64(bytesDiff*8) / elapsed / 1_000_000 // Mbps

			// Get current GCC target
			targetBitrate := 10_000_000 // Default 10 Mbps
			if gccEstimator != nil {
				targetBitrate = gccEstimator.GetTargetBitrate()
			}
			targetMbps := float64(targetBitrate) / 1_000_000

			avgFrameSize := float64(lastFrameSize) / 1024 // KB

			log.Printf("📤 Sending: %.2f Mbps (pion→aiortc) | Target: %.2f Mbps | Frame: %.1f KB | Frames: %d",
				bitrate, targetMbps, avgFrameSize, framesSent)
		}

		lastBytes = bytesSent
		lastTime = now
	}
}

func monitorSendingGCC() {
	// Wait for GCC to stabilize
	time.Sleep(3 * time.Second)

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	callCount := 0
	for range ticker.C {
		callCount++
		if gccEstimator == nil {
			log.Println("⚠️ GCC estimator not ready yet")
			continue
		}

		// Get current target bitrate from GCC
		targetBitrate := gccEstimator.GetTargetBitrate()
		targetMbps := float64(targetBitrate) / 1_000_000

		log.Printf("📤 Sending GCC: %.2f Mbps (pion→aiortc) [call #%d, raw=%d bps]", targetMbps, callCount, targetBitrate)

		// Extra debug: Check if value has changed
		if callCount > 1 && targetBitrate == 10_000_000 {
			log.Printf("⚠️  GCC STUCK: Still at 10 Mbps after %d calls!", callCount)
		}
	}
}

func monitorTrackStats(track *webrtc.TrackRemote) {
	// Wait for stats getter to be ready
	time.Sleep(2 * time.Second)

	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	var lastBytes uint64
	var lastTime time.Time

	for range ticker.C {
		if statsGetter == nil {
			log.Println("⚠️  Stats getter not ready yet")
			continue
		}

		s := statsGetter.Get(uint32(track.SSRC()))
		now := time.Now()

		inbound := s.InboundRTPStreamStats
		if inbound.PacketsReceived == 0 {
			continue // Stats not populated yet
		}

		// Calculate bitrate
		if !lastTime.IsZero() {
			elapsed := now.Sub(lastTime).Seconds()
			bytesDiff := inbound.BytesReceived - lastBytes
			bitrate := float64(bytesDiff*8) / elapsed / 1_000_000 // Mbps

			// Jitter is in RTP timestamp units. For video (90kHz clock): jitter_ms = jitter / 90
			jitterMs := inbound.Jitter / 90.0

			log.Printf("📥 Receiving: %.2f Mbps (aiortc→pion) | Packets: %d | Lost: %d | Jitter: %.2fms",
				bitrate, inbound.PacketsReceived, inbound.PacketsLost, jitterMs)
		}

		lastBytes = inbound.BytesReceived
		lastTime = now
	}
}

func consumeTrack(track *webrtc.TrackRemote) {
	buf := make([]byte, 1500)
	count := 0
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ticker.C:
			log.Printf("📦 Packets: %d in last 5s", count)
			count = 0
		default:
			_, _, err := track.Read(buf)
			if err != nil {
				if err != io.EOF {
					log.Printf("Track read error: %v", err)
				}
				return
			}
			count++
		}
	}
}

func monitorRTCP(receiver *webrtc.RTPReceiver) {
	// Monitor incoming RTCP packets
	senderReportCount := 0
	twccCount := 0
	ticker := time.NewTicker(5 * time.Second)
	defer ticker.Stop()

	log.Println("📡 TWCC: Monitoring for incoming TWCC feedback from receiver...")

	for {
		select {
		case <-ticker.C:
			if senderReportCount > 0 || twccCount > 0 {
				log.Printf("📊 Incoming RTCP (5s): SR=%d, TWCC=%d", senderReportCount, twccCount)
				if twccCount > 0 {
					log.Printf("📡 TWCC: Received %d feedback packets (GCC should update!)", twccCount)
				} else {
					log.Printf("⚠️  TWCC: NO feedback received - GCC cannot adapt!")
				}
				senderReportCount = 0
				twccCount = 0
			}
		default:
			packets, _, err := receiver.ReadRTCP()
			if err != nil {
				if err != io.EOF {
					log.Printf("RTCP read error: %v", err)
				}
				return
			}

			for _, pkt := range packets {
				switch p := pkt.(type) {
				case *rtcp.SenderReport:
					senderReportCount++
				case *rtcp.TransportLayerCC:
					// TWCC feedback from receiver - this is what we want!
					twccCount++
					if twccCount <= 5 || twccCount%50 == 0 {
						log.Printf("📡 TWCC #%d: Received feedback with %d packets (base_seq=%d, ref_time=%d, fb_count=%d)",
							twccCount, p.PacketStatusCount, p.BaseSequenceNumber, p.ReferenceTime, p.FbPktCount)
					}
				default:
					// Log unknown RTCP packet types
					if twccCount == 1 {
						log.Printf("📬 RTCP: Received other packet type: %T", pkt)
					}
				}
			}
		}
	}
}

func checkTWCC(sdp string) {
	twccURIs := []string{
		"transport-wide-cc",
		"transport-cc",
		"draft-holmer-rmcat",
	}

	found := false
	for _, uri := range twccURIs {
		if strings.Contains(sdp, uri) {
			log.Printf("✅ TWCC extension found: %s", uri)
			found = true
			break
		}
	}

	if !found {
		log.Println("❌ TWCC extension NOT found in SDP")
	}
}

func signaling(serverAddr string, offer webrtc.SessionDescription) (*webrtc.SessionDescription, error) {
	data, err := json.Marshal(offer)
	if err != nil {
		return nil, err
	}

	resp, err := http.Post(serverAddr+"/offer", "application/json", strings.NewReader(string(data)))
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("status %d: %s", resp.StatusCode, body)
	}

	var answer webrtc.SessionDescription
	if err := json.NewDecoder(resp.Body).Decode(&answer); err != nil {
		return nil, err
	}

	return &answer, nil
}
